exclude:
  - ./requirements-dev.txt
  - ./requirements-ram.txt
  - ./requirements-rtd.txt

# initial commit; ignore vulnerabilities
ignore:
  - vulnerability: GHSA-xqr8-7jwr-rhp7
    package:
      name: certifi
      version: 2022.6.15
      type: python
  - vulnerability: GHSA-v3c5-jqr6-7qm8
    package:
      name: future
      version: 0.18.2
      type: python
  - vulnerability: GHSA-9j59-75qj-795w
    package:
      name: pillow
      version: 8.4.0
      type: python
  - vulnerability: GHSA-8vj2-vxx3-667w
    package:
      name: pillow
      version: 8.4.0
      type: python
  - vulnerability: GHSA-m2vv-5vj5-2hm7
    package:
      name: pillow
      version: 8.4.0
      type: python
  - vulnerability: GHSA-8gq9-2x98-w8hf
    package:
      name: protobuf
      version: 4.21.2
      type: python
  - vulnerability: GHSA-9q9m-c65c-37pq
    package:
      name: reportlab
      version: 3.6.8
      type: python
