repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-ast
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, staging, --branch, production]
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.991
#    hooks:
#    -   id: mypy
#        exclude: docs\*
